language: python
dist: xenial
cache: false
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
matrix:
  include:
    - python: '3.7'
      env:
        - TOXENV=check
#     - python: '3.7'
#       env:
#         - TOXENV=docs
    - python: '3.7'
      env:
        - TOXENV=py37
    - python: '3.8'
      env:
        - TOXENV=py38
#     - env:
#         - TOXENV=pypy3
#         - TOXPYTHON=pypy3
#       python: 'pypy3'
before_install:
  - echo -e "\n[global]\nuse ntlmv2 = yes\ntds version = 7.3" >> /tmp/freetds.conf
  - sudo cp /tmp/freetds.conf /etc/
  - cat /etc/freetds.conf
  - python --version
  - uname -a
  - lsb_release -a || true
install:
  - python -mpip install --progress-bar=off pip>=19.3.1 setuptools>=42.0.2 tox virtualenv>=16.7.8
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
script:
  - tox -v
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
notifications:
  email:
    on_success: never
    on_failure: always
